server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  profiles:
    group:
      local: key
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8778/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-secret: ''
            client-id: ''
            client-name: Naver
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  jpa:
    database: h2
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:JPATest
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
